INSERT INTO md_district (district_id, district_name, province_id) VALUES (51,'27 de Noviembre',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (41,'Ambar',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (11,'Ancon',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (72,'Andajes',9);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (69,'Arahuay',8);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (49,'Atavillos Alto',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (50,'Atavillos Bajo',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (54,'Aucallama',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (58,'Barranca',7);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (29,'Bellavista',4);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (12,'Breña',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3081,'Cajatambo',3078);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (38,'Caleta de Carquin',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (28,'Callao',4);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (63,'Canta',8);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (13,'Carabayllo',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (30,'Carmen de la Legua',4);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (74,'Caujul',9);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (47,'Chancay',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (42,'Checras',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (75,'Cochamarca',9);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (14,'Comas',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3082,'Copa',3078);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (15,'El Agustino',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3085,'Gorgor',3078);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (34,'Huacho',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (37,'Hualmay',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (68,'Huamantanga',8);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3083,'Huancapon',3078);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (46,'Huaral',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (65,'Huaros',8);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (35,'Huaura',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (56,'Ihuari',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (22,'Independencia',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (16,'Jesus Maria',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (31,'La Perla',4);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (32,'La Punta',4);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3049,'La Victoria',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (66,'Lachaqui',8);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (55,'Lampian',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (43,'Leoncio Prado',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (10,'Lima Cercado',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3086,'Lince',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (27,'Los Olivos',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3088,'Lurigancho-Chosica',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (17,'Magdalena del Mar',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3084,'Manás',3078);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3249,'Mi Peru',4);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (73,'Navan',9);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (70,'Oyon',9);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (52,'Pacaraos',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (44,'Paccho',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (71,'Pachangara',9);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (62,'Paramonga',7);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (59,'Pativilca',7);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (18,'Pueblo Libre',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (19,'Puente Piedra',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (20,'Rimac',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3051,'San Antonio de Chaclla',3050);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (67,'San Buenaventura',8);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (21,'San Isidro',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (25,'San Juan de Lurigancho',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (23,'San Martin de Porres',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (24,'San Miguel',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (48,'San Miguel de Acos',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (3087,'Santa Anita',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (53,'Santa Cruz de Andamarca',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (45,'Santa Leonor',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (40,'Santa Maria',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (26,'Santa Rosa',3);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (64,'Santa Rosa de Quives',8);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (39,'Sayan',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (57,'Sumbilca',6);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (60,'Supe',7);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (61,'Supe Puerto',7);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (36,'Vegueta',5);
INSERT INTO md_district (district_id, district_name, province_id) VALUES (33,'Ventanilla',4);
